USE SuperHeroesDb
GO

CREATE TABLE SuperHero
(
[Id] INT IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(50) NULL,
[Alias] NVARCHAR(50) NULL,
[Origin] NVARCHAR(50) NULL
);
GO

CREATE TABLE Assistant
(
[Id] INT IDENTITY(1,1) PRIMARY KEY,
[Name] NVARCHAR(50) NULL
);
GO

CREATE TABLE Power
(
[Id] INT IDENTITY(1,1) PRIMARY KEY,
[Name] NVARCHAR(50) NULL,
[Description] NVARCHAR(200)
);
GO